[project]
name = "color-picker"
version = "0.1.0"
description = "TUI color picker"
authors = [
  { name = "bag1s3k", email = "174890936+bag1s3k@users.noreply.github.com" },
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "mss>=10.2.0",
  "pyfiglet>=1.0.4",
  "pynput>=1.8.2",
  "rich>=15.0.0",
  "textual>=8.2.5",
]

[dependency-groups]
dev = ["ruff>=0.15.13", "textual-dev>=1.8.0"]

[project.scripts]
color-picker = "color_picker:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
